#!/bin/bash 

export ID=$1
if [[ -z $ID ]]; then exit 1; fi

# export LOCAL_IP=$(/sbin/ifconfig en0 | sed '/inet\ /!d;s/.*inet //g;s/\ .*//g')
export LOCAL_IP=192.168.1.114
export TOKEN=66ea6c39d90bfab819bede8661041181

export NODE=${USER}-$LOCAL_IP-$ID
export LOCAL_PORT=400${ID}
export LOCAL_PPORT=700${ID}

echo Starting $NODE on $LOCAL_PORT:$LOCAL_PPORT

CID=$(docker run -d --name $NODE -p $LOCAL_PPORT:$LOCAL_PPORT -p $LOCAL_PORT:$LOCAL_PORT coreos/etcd -peer-addr $LOCAL_IP:$LOCAL_PPORT -addr $LOCAL_IP:$LOCAL_PORT -name $NODE -cors '*' -discovery https://discovery.etcd.io/${TOKEN})
docker logs $CID
